### ISSUE TITLE
Add a way to turn off messages in alpha.fd.multidim()

### ISSUE THREAD

**Issue by Rekyt** [CmlMagneville/mFD#16]
Hello `mFD` maintainers 👋 (mostly @CmlMagneville I suppose!)

I'm experimenting with the package especially the `alpha.fd.multidim()` function.
However, when using it multiple times I find it quite verbose because it prints a lot in the console and there is no way to turn the message from https://github.com/CmlMagneville/mFD/blob/a6af5670fd1b4042ba54b6b9050b67e83159bc38/R/alpha_fd_multidim.R#L510-L511 off.
I would suggest adding a `verbose` argument (TRUE by default) that would allow to turn it off.
I can submit a PR if you want :)

**Comment by Rekyt** [comment]
A note about the `print()` function: maybe using `message()` would be a better alternative (see https://stackoverflow.com/a/36700294) because the messages can be removed by `suppressMessages()` by the user, and then there are no need for a `verbose` argument?

**Comment by CmlMagneville** [comment]
Hi @Rekyt 👋

Being able to turn on/off messages is indeed a good idea! You can submit a PR if you want :)

I think that using a `verbose` argument is more user-friendly than turning `print()` function into `message()` function, so I prefer this option.

Thank your for your help!
