### ISSUE TITLE
error within quality.fspaces

### ISSUE THREAD

**Issue by mthompson89** [CmlMagneville/mFD#19]
Hello, 
I am relatively new to github so bare with me if this should have been a pull request.

incredible job on this package. I have been looking for something like this for a while now. I ran into an issue when I was running `quality.fspaces()` if you set the fdist_scaling to `TRUE` you get an error ` object 'details_deviation' not found` looking at the source code it looks like this is because in line 89, `details_deviation` is not defined before calling it within `if (TRUE %in% fdist_scaling)` whereas it looks like it is for `if (FALSE %in% fdist_scaling)`. I seemed to fix the issue by creating the object in line 85.
```
  if (TRUE %in% fdist_scaling) {
    df_distsp_scaled <- data.frame(df_distsp[, c("sp.x", 
                                                 "sp.y", "tr")], apply(df_distsp[, fspaces_nm], 2, 
                                                                       function(x) {
                                                                         x/max(x) * max(df_distsp[, "tr"])
                                                                       }))
    details_deviation <- list(df_distsp_scaled = df_distsp_scaled)
    details_fspaces$pairsp_fspaces_dist_scaled <- df_distsp_scaled
    dev_distsp_scaled <- data.frame(df_distsp_scaled[, c("sp.x", 
                                                         "sp.y")], df_distsp_scaled[, fspaces_nm] - df_distsp_scaled[, 
                                                                                                                     "tr"])
    details_deviation$dev_distsp_scaled <- dev_distsp_scaled
```
hope this helps and thanks again for all the work you put in!

**Comment by CmlMagneville** [comment]
Hello,

Thank you for raising this issue with `quality.fspaces()!` 
It has been solved: you were right there was a problem with an uncreated object. The Github version is now up-to-date and works fine ;)
