### ISSUE TITLE
Problems with "asb_sp_w" function

### ISSUE THREAD

**Issue by AlexArevalo1** [CmlMagneville/mFD#21]
Hi everyone!
I would like to develop my functional diversity analysis with mFD, but I found a problem and I think that is due to my "baskets_fruits_weights" (weights) spreadsheet, although the original "baskets_fruits_weights" of mFD package and my data are similar (assemblages (records) in rows and species in columns):

> baskets_fruits_weights
>           apple apricot banana currant blackberry blueberry cherry grape
> basket_1    400       0    100       0          0         0    150     0
> basket_2    200       0    400       0          0         0    250     0
> basket_3    200       0    500       0          0         0    250     0
> ________
> # Load data: sps = baskets_fruits_weights
> sps <- read.table("Sps_RLQ-.txt",header=TRUE,fill = TRUE)
> sps
>        Ca_un Cu_pa Da_le Da_sp Di_ma Ei_ba Le_pa Le_wi Ma_am Ma_ne My_ac My_tr
> PAI01      0     2     9     0     0     0     1     0     0     0     2     0
> PAI02      0     1     0     1     0     0     0     0     1     0     1     0
> PAI04      0     2     4     1     0     0     0     0     0     0     2     2
> PAI05      0     0     0     1     0     0     0     0     0     0     4     0

When I do str function:

> > str(baskets_fruits_weights)
>  int [1:10, 1:25] 400 200 200 300 200 100 100 0 0 350 ...
>  - attr(*, "dimnames")=List of 2
>   ..$ : chr [1:10] "basket_1" "basket_2" "basket_3" "basket_4" ...
>   ..$ : chr [1:25] "apple" "apricot" "banana" "currant" ...
> _______________________
> > str(sps)
> 'data.frame':	80 obs. of  19 variables:
>  $ Ca_un : int  0 0 0 0 0 0 0 0 1 0 ...
>  $ Cu_pa : int  2 1 2 0 4 1 1 0 2 0 ...
>  $ Da_le : int  9 0 4 0 2 0 5 0 24 14 ...
>  $ Da_sp : int  0 1 1 1 0 0 0 1 2 2 ...

Finally, when I run "Summary of the assemblages * species dataframe (asb_sp_fruits_summ <- mFD::asb.sp.summary(asb_sp_w = ...)" for my data, it appears a warning message: 

> > asb_sp_sps_summ <- mFD::asb.sp.summary(asb_sp_w = sps)
> **Error in check.asb.sp.w(asb_sp_w) :** 
>   **The argument 'asb_sp_w' must be a matrix**.

Please, could you tell me how can I resolve this problem?

Thanks!

Alexander Arévalo.
PhD Candidate in Biology-Ecology (INPA)

**Comment by ahasverus** [comment]
Hi Alexander,
The object `asb_sp_w` must be a `matrix`, but in your case is a `data.frame` as you read data from a text file. Before using any function of the `mFD` package, you need to convert this `data.frame` into a `matrix`. 
For instance, you can run: `sps <- data.matrix(sps)`
Then you might be able to use `mFD::asb.sp.summary(sps)`
Hope this helps.
Cheers,
Nicolas.

**Comment by AlexArevalo1** [comment]
Hi Nicolas, 
That was the problem. Thank you so much for your response.

Cheers,
Alexander.
