### ISSUE TITLE
Small typo in quality.fspaces()

### ISSUE THREAD

**Issue by Klemet** [CmlMagneville/mFD#23]
Hello there !

While shammingly copying/pasting content from the [General Workflow](https://cmlmagneville.github.io/mFD/articles/mFD_general_workflow.html) to R studio in order to try `mFD`, I've stumbled upon a typo in quality.fspaces().

When I tried to used the code from the following sentence in section `4.1`:

> Both quality metrics can be used with deviation_weighting = c("absolute", "squared").

I noticed that using `deviation_weighting = c("absolute", "squared")` doesn't work, as it returns the error:

```bash
Error in mFD::quality.fspaces(sp_dist = distanceBetweenSpeciesWithTraits,  : 
  Input 'deviation_weighting' should be 'absolute' and/or 'squarred'.
```

The difference is in the presence of two `r` in the word `squared`. Using `deviation_weighting = c("absolute", "squarred")` works properly.

However, `squarred` is, to my understanding, not the proper grammar for the word. It should be `squared`, as in the documentation.

Thus, I suggest editing [those lines](https://github.com/CmlMagneville/mFD/blob/47ac4bc30b5905381b8e122f7aac63e7661520dd/R/quality_fspaces.R#L157) in the code.

Thanks again for the detailed documentation, it's great !

**Comment by CmlMagneville** [comment]
Hi Clement!

Thank you for your feedback and for detecting this typo! 

This issue is fixed and `squared` is now well written 👌

**Comment by Klemet** [comment]
Most welcome, and thank you again for your work !
