### ISSUE TITLE
Potential performance issue of alpha.fd.multidim() with large assemblage dataset

### ISSUE THREAD

**Issue by Klemet** [CmlMagneville/mFD#24]
Hello again!

I was curious to know if a performance problem that I'm having could be due to an issue in the package, or if I should do things differently considering the data that I have to deal with.

Basically, my goal was to compute all of the alpha functional diversity measure with `alpha.fd.multidim()` for each forested pixel in a landscape simulated via the LANDIS-II model.

LANDIS-II outputs "biomass rasters" for the 17 tree species that I'm simulating which indicate what is the biomass for a given species in each pixel of the landscape. I've been using these to create an assemblage matrix where every line is a pixel, and every column contains the biomass of the species in the cell.

Here is how the assemblage matrix looks like:

|    | ABIE.BAL| ACER.RUB| ACER.SAH| BETU.ALL| BETU.PAP| FAGU.GRA| LARI.LAR| PICE.GLA| PICE.MAR| PICE.RUB| PINU.BAN| PINU.RES| PINU.STR| POPU.TRE| QUER.RUB| THUJ.SPP.ALL| TSUG.CAN|
|:---|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|------------:|--------:|
|569 |     1810|        0|        0|        0|      138|        0|        0|        0|     3339|        0|        0|        0|        0|        0|        0|            0|        0|
|570 |     1810|        0|        0|        0|      138|        0|        0|        0|     3339|        0|        0|        0|        0|        0|        0|            0|        0|
|571 |     1810|        0|        0|        0|      138|        0|        0|        0|     3339|        0|        0|        0|        0|        0|        0|            0|        0|
|572 |     1810|        0|        0|        0|      138|        0|        0|        0|     3339|        0|        0|        0|        0|        0|        0|            0|        0|
|573 |     1810|        0|        0|        0|      138|        0|        0|        0|     3339|        0|        0|        0|        0|        0|        0|            0|        0|
|574 |     1318|        0|        0|        0|      527|        0|        0|        0|     3199|        0|        0|        0|        0|        0|        0|            0|        0|
|575 |     1318|        0|        0|        0|      527|        0|        0|        0|     3199|        0|        0|        0|        0|        0|        0|            0|        0|
|576 |     2413|        0|        0|        0|      332|        0|        0|        0|     2001|        0|        0|        0|        0|        0|        0|            0|        0|
|577 |     2413|        0|        0|        0|      332|        0|        0|        0|     2001|        0|        0|        0|        0|        0|        0|            0|        0|
|578 |     2413|        0|        0|        0|      332|        0|        0|        0|     2001|        0|        0|        0|        0|        0|        0|            0|        0|

I've followed the [general workflow](https://cmlmagneville.github.io/mFD/articles/mFD_general_workflow.html) carefully so as to select the functional space that I would use, and I also took care to keep only the assemblages (pixels) where the number of species present was superior to the number of PCoA axis that I was using to compute the alpha functional diversity indices.

The problem comes when it's time to use `alpha.fd.multidim()` on my assemblage matrix, which has around 4 million rows (as my simulated landscape has about 4 million forested pixels). After leaving the functioning running for the whole night on my computer, the display of the % of progress (which normally displayed using `verbose = TRUE`) did not even start.

My computer has 16 GB of RAM, and an Intel i7-6700HQ CPU running at 2.60GHz; not the best, but far from being the worst. RAM-wise, Rstudio oscillated to a usage of 8-11GB periodically throughout the night while the function was running, without any change. I never ran out of RAM, and have a big page file installed on a SSD just in case; so I don't think that the problem is due to a lack of RAM here.

I tried to do some tests by using subsets of the assemblage matrix : 1 000 rows, 10 000 rows, etc., to see how `alpha.fd.multidim()` was behaving. It looks like the bigger the assemblage matrix, the more time the function spends in the initialization phase ([before the loop that starts at line 302 of the related file](https://github.com/CmlMagneville/mFD/blob/5c796c7774e4f6418c4007a5893e89cfbb5e5a28/R/alpha_fd_multidim.R#L302)) before starting to compute the indices (and thus starting to display the percentage of progress). When going above 100 000 rows, this initialization phase becomes very long.

I guess that I could make subsets of my assemblage matrix, compute the indices on these subsets, and then stitch everything back up together; but maybe I'm missing something. Would you have any tips or advice concerning this issue ?

**Comment by CmlMagneville** [comment]
Hello Clément,

There is no other way to speed up the process: you can subsample your data and also unable the checking by changing `check_input = FALSE` in the inputs. The first lines are mostly checks so may be unabling them will speed up a little bit the process. But with 4 million rows, there is no doubt that it will take some time...

Hope it helps,

Camille

**Comment by Klemet** [comment]
Oh, yes ! I forgot to add that I had set `check_input = FALSE`. I'm still wondering what's happening; when reaching 100 000 assemblages, it's like the initialization phase time increases exponentially, up to the point to it will just not run anymore.

Subsetting and subsampling are still valid solutions, yes; but I imagine that this problem will impact any study that uses raster data.
