### ISSUE TITLE
Issue with sequential row names  in asb.sp.summary()

### ISSUE THREAD

**Issue by Klemet** [CmlMagneville/mFD#25]
Hello again !

I just noticed that it seemed that when the user wants to have sequential row names in their assemblage matrix (row names starting from 1 and ending at `length(assemblageMatrix`), `asb.sp.summary()` returns an error saying that no row names have been set (even if they have been set with something like `rownames(assemblageMatrix) <- seq (1, length(assemblageMatrix))`).

Of course, most of the time, the assemblage names will not be a sequence of number starting from 1; but in some cases (like me, where assemblages are pixels in a raster), this can be the case. In this type of moment, the user has to make "fake" row names that does not correspond to the row names that are useful to them for the function to work.

I imagine that this error is here to prevent row names from being sequential, in case the user forgot or doesn't know that they can be set. But maybe a warning at the end of the function is enough ?

**Comment by CmlMagneville** [comment]
Hello Clément!

We decided to force the user to have assemblages names to prevent errors in the analysis process so the only way is to set row names as you did. I guess the renaming process is not that long ;)

Thank you for your many feedbacks on the package!

Camille

**Comment by Klemet** [comment]
Alright, I guess that I can understand ! It's just that row names can be used to access entries in vector or rasters; but with a couple of functions, it's completely feasible, as you said.

Thank you for your answers !
