### ISSUE TITLE
Issue w/ handing binary variables between mFD::funct.dist() and gawdis()

### ISSUE THREAD

**Issue by Jaxsonp10** [CmlMagneville/mFD#26]
When trying to run the function mFD::funct.dist() with binary variables (both ordered and nominal), the function will not run because gawdis requires binary traits to be numeric (even if they're in stored as strings). 

I don't know if this really counts as a bug, but it did trip me up. I had to use gawdis separate from mFD:funct.dist() to calculate the dissimilarity.

**Comment by CmlMagneville** [comment]
Hello!
It is strange that the `mFD::funct.dist()` function does not work with your data because it is indeed working with mine with ordered and nominal variables. 
What is exactly the Error message you got?
Camille
