### ISSUE TITLE
Issue computing indices with alpha.fd.fe()

### ISSUE THREAD

**Issue by Alexia126** [CmlMagneville/mFD#27]
Function does not recognize properly the input provide for a previous computed list, resulting in the following error even tho information was already verified separately and matched

Error in mFD::alpha.fd.fe(asb_sp_occ = asb_sp_bee_occ, sp_to_fe = sp_to_fe_bee,  : 
  All species in species*assemblage occurence matrix  should be in the input 'sp_to_fe'. Please check that the function 'sp.to.fe' was applied on trait values of the same set of species.

Do not know if it counts as a bug but I just checked a bunch of times following the tutorial and simply does not work 
https://cmlmagneville.github.io/mFD/articles/How_to_deal_with_Functional_Entities.html

**Comment by CmlMagneville** [comment]
Hi!
The `alpha.fd.fe()` function works fine with the fruits data of the package on my computer. Can you provide any information about your data so I can help you?

**Comment by Alexia126** [comment]
Of course!, I am currently working with these files land was trying to calculate FE divesiry Index and also functional diversity through Hill numbers however the same error keeps poping :/  and don't really understand why because  I'm using the output date from previous functions and yet :/.

Thank you so much for your help!

[Traits and species.txt](https://github.com/CmlMagneville/mFD/files/8865684/Traits.and.species.txt)
[Species and ensambles.txt](https://github.com/CmlMagneville/mFD/files/8865685/Species.and.ensambles.txt)
[Trait descriptors.txt](https://github.com/CmlMagneville/mFD/files/8865686/Trait.descriptors.txt)

**Comment by Alexia126** [comment]
Also I was following the tutorial for Functional entities (https://cmlmagneville.github.io/mFD/articles/How_to_deal_with_Functional_Entities.html)

and this error poped up when I was trying to use this fuction sp.to.fe
Error in mFD::sp.to.fe(sp_tr = fruits_traits, tr_cat = fruits_traits_cat,  : 
  Trait names differ between species x traits data frame and traits x category data.frame. Please check.

which confused me a bit more

**Comment by CmlMagneville** [comment]
I'll have a look at your data as soon as possible!

For the problem you encounter while running the Functional Entities tutorial, there was a code chunk missing to load the `fruits_traits_cat` data (coded but not appearing). It can may be explain the error you got. Try running it again and tell me.

**Comment by Alexia126** [comment]
Thank you so much!, I'd really appreciate it because I just double checked with a lab partner who suggested not to use special characters like Ñ or accent marks which I immediately changed, then re run the data and once again same error popped up :( and it is the same whenever I try to use alpha.fd.hill as well, so I am bit lost tbh. 

Error in alpha.fd.hill(asb_sp_w = SppXEns, sp_dist = sp_dist_bee, q = c(0,  : 
  Mismatch between names in species*weight and species distances matrix. Please check.
  
I attached the data without special characters
[bee_traits_cat.txt](https://github.com/CmlMagneville/mFD/files/8871707/bee_traits_cat.txt)
[bee_traits.txt](https://github.com/CmlMagneville/mFD/files/8871708/bee_traits.txt)
[vegetation_bee_abundance.txt](https://github.com/CmlMagneville/mFD/files/8871710/vegetation_bee_abundance.txt)

**Comment by CmlMagneville** [comment]
Hi,

Can you send me your data as rds files? I have trouble opening them

**Comment by Alexia126** [comment]
Hello, 

It is ok!, I simplify all the names in the matrix to avoid issues with the characters and worked like charm 

Thank you so much for your help in anycase!

**Comment by CmlMagneville** [comment]
Ok, great! Don't hesitate if you have any other question ;)
