### ISSUE TITLE
alpha.fd.multidim

### ISSUE THREAD

**Issue by beifenging** [CmlMagneville/mFD#28]
When calculating alpha.fd.multidim，“Number of species should strictly be higher than the number of axes to compute the convex hull. It is not the case for 13_A. Remove this assemblage or decrease the number of functional axes. FRic can not be computed here”.
You can not assign NA to site(or plot) that can not be calculated.
Just like FD package.

**Comment by CmlMagneville** [comment]
Hi,
Yes it will may be be coded in a next version of the `mFD` package, however for now, you can first compute separately the indices with no richness constraints and then, filter your assemblages and compute the indices with richness constraint.
