### ISSUE TITLE
alpha.multidim.plot How to plot species detected in both assemblages in a third color

### ISSUE THREAD

**Issue by sroblet** [CmlMagneville/mFD#39]
Hi,
Thanks again Camille for your amazing package.
I just have a question related to the function alpha.multidim.plot.
In the example shown in your tutorial, you show us how to plot two assemblages and to attribute a given color for species present in each of these assemblages. Is there a way to add a third color to the graph to hilight species present in BOTH assemblages ?
Thanks,

**Comment by CmlMagneville** [comment]
Hi,
I'm glad that the `mFD` package is helping you in your analysis.
There is currently no option in the `alpha.multidim.plot()` fonction to do so. However, you can use functions used inside `alpha.multidim.plot()` to do that, by creating a "false" assemblage gathering species present both in the two assemblages you want to plot. In the following tutorial we have showed how to use these functions: https://cmlmagneville.github.io/mFD/articles/Customised_plots.html 
I hope it helps,
Camille
**Note:** For more questions about the package or challenges you encounter while using for your analyses, contact me by email 😊 - **Issues are made for code bugs and fix** 🐛 (I'll try to do new page on the mFD website to compile the FAQs soon)
