### ISSUE TITLE
ERROR in funct.dist - if statement

### ISSUE THREAD

**Issue by ahasverus** [CmlMagneville/mFD#41]
The function `funct.dist()` returns an error at the condition: `if (all(tr_cat$trait_type == rep("Q", nrow(tr_cat)))) { ... }`

I will submit a PR with a fix.

**Comment by ahasverus** [comment]
Sorry, already fixed by you ;)

**Comment by CmlMagneville** [comment]
Thanks for keeping an eye on mFD ;)
