### ISSUE TITLE
Issues with Non euclidean distance using function mFD

### ISSUE THREAD

**Issue by Taiyou187** [CmlMagneville/mFD#42]
Hi,
I'm trying to use mFD with fish data and I'm running in to issues with non-euclidean distances.  
Any help or suggestions would be appreciated.
My taxa data consists of 18 sites x 59 taxa and my trait data consists of 59 taxa x 2 traits.  
The traits are 1 non-ordered factor, 1 ordered factor 
When I run mFD and get the warning messages:
Warning message for mFD::funct.dist
In mFD::funct.dist(sp_tr = fruits_traits, tr_cat = fruits_traits_cat,  :
  Functional distance between some species is equal to 0. You can choose to gather species into Functional Entities gathering species with similar traits values.
Warning message for mFD::quality.fspaces
1: In ade4::is.euclid(sp_dist) : Zero distance(s)
2: In mFD::quality.fspaces(sp_dist = sp_dist_fruits, maxdim_pcoa = 10,  :
  Functional distance between some species is equal to 0 (explains the Warning message 1). You can choose to gather species into Functional Entities gathering species with similar traits values.

**Comment by CmlMagneville** [comment]
Hi,

This warning message (not an error one) is saying that some species pairs have a functional distance which equals 0, that is to say that they have the same combination of traits (the same values of traits for all the traits you are studying). It is quite normal as you are using only two non-continuous traits to describe species.
I don't know what is your study system and your research question, but increasing the number of traits you are using might be a good idea - studies usually use 5 traits or more.
Moreover, you can then group species into functional entities which are groups of species with same trait values when species are described with categorical and/or ordinal traits (cf https://cmlmagneville.github.io/mFD/articles/How_to_deal_with_Functional_Entities.html).

Camille

**Note:** For more questions about how the package works or challenges you encounter while using for your analyses, contact me by email  - **Issues are made for code bugs and fix** 🐛 (I'll try to do new page on the `mFD` website to compile the FAQs soon)

**Comment by Taiyou187** [comment]
Hi,

Thank you for your reply.
This is my new field, and I try to learn how to analyze by R.
I appreciate your help.

Best,

Nhat
