### ISSUE TITLE
Trouble with mFD package tutorial

### ISSUE THREAD

**Issue by Gaspar551** [CmlMagneville/mFD#44]
I am trying to reproduce the codes in the tutorial "mFD: General Workflow" by Camille Magneville. Most codes function ok, but all codes related to plot yield the following message: 
Error in Ops.data.frame(guide_loc, panel_loc) : # ‘==’ only defined for equally-sized data frames

And nothing is plotted.

Please can you provide a solution for this issue?.

**Comment by CmlMagneville** [comment]
Hi,

Please see Issue #40 :
"The problem comes from the patchwork package, you have to update it (it's working on my computer after the update to vers 1.2.0) 📦"

Camille

**Comment by Gaspar551** [comment]
Thank you very much for your rapid answer!. It is functioning OK now.
Gaspar
    On Sunday, July 7, 2024 at 05:49:50 PM EDT, Camille Magneville ***@***.***> wrote:  
 
 


Hi,

Please see Issue #40 :
"The problem comes from the patchwork package, you have to update it (it's working on my computer after the update to vers 1.2.0) 📦"

Camille
